---
- name: Basic GCE config playbook
  hosts: all
  tasks:
  - name: launch msql-server container
    docker_container:
      name: db
      image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
      state: started
      env:
        ACCEPT_EULA=Y
        SA_PASSWORD=yourStrong(!)Password
        MSSQL_PID=Express
      ports:
      - "1433:1433"
    become: true