---
- name: Basic GCE config playbook
  hosts: all
  tasks:
  - name: launch postgres container
    docker_container:
      name: postgres_db
      image: postgres:13.0-alpine
      state: started
      restart: yes
      restart_policy: always
      env:
        POSTGRES_USER=test_postgres_user
        POSTGRES_PASSWORD=changeme
        POSTGRES_DB=sample_db
      volumes: 
        /pgdata:/var/lib/postgresql/data
      ports:
      - "9372:5432"
    become: true